# Production connection
spring.datasource.url=jdbc:mariadb://172.16.144.51:3306/s2507110321?useSSL=false
spring.datasource.username=s2507110321
spring.datasource.password=1234

# Cookie Settings
cookie.secure=false
