# 1. local ???? Docker MariaDB ?? ??
spring.datasource.url=jdbc:mariadb://localhost:3307/crowd_fund?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
