# RDS connection
spring.datasource.url=jdbc:mariadb://${DB_URL}:3306/crowd_fund?useSSL=true&trustServerCertificate=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Cookie Settings
cookie.secure=true
